---
- name: Deploy sharmili-devops-lab.war to Tomcat
  hosts: tomcat-server
  become: yes
  vars:
    war_name: sharmili-devops-lab.war
    tomcat_webapps_dir: /opt/tomcat/webapps
  tasks:
    - name: Copy WAR to Tomcat webapps
      copy:
        src: "{{ war_name }}"
        dest: "{{ tomcat_webapps_dir }}/{{ war_name }}"
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
 

