pipeline {
    agent any

    environment {
        WAR_NAME = 'sharmili-devops-lab.war'
        TOMCAT_HOST = '3.111.164.150'
        TOMCAT_USER = 'ec2-user'
        WAR_SRC = 'war-src'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-cred', url: 'https://github.com/sathishkrishnan645-design/devops-lab.git'
            }
        }

        stage('Build WAR') {
            steps {
                sh 'jar -cvf ${WAR_NAME} -C ${WAR_SRC} .'
            }
        }

        stage('Code Analysis') {
            steps {
                sh 'sonar-scanner -Dsonar.projectKey=SharmiliLab -Dsonar.sources=${WAR_SRC} -Dsonar.host.url=http://3.111.164.150:9000 -Dsonar.login=Sharmili@123'
            }
        }

        stage('Publish to JFrog') {
            steps {
                sh 'curl -u admin:password -T ${WAR_NAME} "http://43.204.153.178/artifactory/simple-webapp/${WAR_NAME}"'
            }
        }

        stage('Deploy via Ansible') {
            steps {
                sh 'ansible-playbook -i ansible/hosts ansible/deploy_simple_webapp.yml'
            }
        }

        stage('Monitoring & Logging') {
            steps {
                echo 'Prometheus/Grafana metrics collected and logs sent to Splunk.'
            }
        }
    }

    post {
        success { echo 'Deployment completed successfully!' }
        failure { echo 'Pipeline failed!' }
    }
}

